---
title: "Clinical Characteristics"
author: "Elad Deiss-Yehiely"
date: "2026-04-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Clinical Characteristics Table
```{r}
library(gtsummary)

sam_sub_age4_demotable <- sam_sub_age4
sam_sub_age4_demotable <- sam_sub_age4_demotable %>%
  left_join(
    formatted_merged_df %>% 
      select(Subject_ID, Group, child...18.months_mediec_c_ab_q1),
    by = c("Subject_ID", "Group")
  )
sam_sub_age4_demotable$child...18.months_mediec_c_ab_q1 <- sam_sub_age4_demotable$child...18.months_mediec_c_ab_q1 == 1

sam_sub_age4_demotable <- sam_sub_age4_demotable %>%
  mutate(
    chronic_rhinitis36m_current = factor(
      chronic_rhinitis36m_current,
      levels = c(FALSE, TRUE),
      labels = c("No chronic rhinitis", "Chronic rhinitis")
    )
  )

sam_sub_age4_demotable <- sam_sub_age4_demotable %>%
  mutate(
    race_white = factor(dem_c_4___1, levels = c(FALSE, TRUE), labels = c("No", "Yes")),
    race_black = factor(dem_c_4___2, levels = c(FALSE, TRUE), labels = c("No", "Yes")),
    race_american_native = factor(dem_c_4___3, levels = c(FALSE, TRUE), labels = c("No", "Yes")),
    race_asian_indian = factor(dem_c_4___4, levels = c(FALSE, TRUE), labels = c("No", "Yes")),
    race_asian = factor(dem_c_4___5, levels = c(FALSE, TRUE), labels = c("No", "Yes")),
    #race_pacific_islander = factor(dem_c_4___6, levels = c(FALSE, TRUE), labels = c("No", "Yes")),
    race_other = factor(dem_c_4___7, levels = c(FALSE, TRUE), labels = c("No", "Yes"))
  )

race_vars <- c("race_white", "race_black", "race_american_native", "race_asian_indian", "race_asian", "race_other")

library(gtsummary)

tbl1 <- sam_sub_age4_demotable %>%
  select(
    chronic_rhinitis36m_current,
    all_of(race_vars),
    sex,
    canoe_site.x,
    child...6.months_ifp_b01,
    pmci_c6___1,
    child...18.months_mediec_c_ab_q1
  ) %>%
  tbl_summary(
    by = chronic_rhinitis36m_current,

    type = list(
      all_of(race_vars) ~ "dichotomous",
      canoe_site.x ~ "categorical",
      sex ~ "categorical",
      child...6.months_ifp_b01 ~ "categorical",
      pmci_c6___1 ~ "categorical",
      child...18.months_mediec_c_ab_q1 ~ "categorical"
    ),

    value = all_of(race_vars) ~ "Yes",

    statistic = all_categorical() ~ "{n} ({p}%)",

    label = list(
      race_white   ~ "White",
      race_black   ~ "Black",
      race_american_native ~ "American or Alaskan Native",
      race_asian_indian ~ "Asian Indian",
      race_asian ~ "Asian",
      race_other ~ "Other race",
      sex ~ "Child sex",
      canoe_site.x ~ "Study site",
      child...6.months_ifp_b01 ~ "Infant ever breastfed at 6 months",
      pmci_c6___1 ~ "Infant born vaginally",
      child...18.months_mediec_c_ab_q1 ~ "Infant given antibiotics by 18 months"
    ),

    missing = "no"
  ) %>%
  add_n() %>%
  add_p(
    test = list(
      all_categorical() ~ "chisq.test",
      all_dichotomous() ~ "fisher.test"
    )
  ) %>%
  bold_labels()

tbl1 <- tbl1 %>%
  modify_table_body(
    ~ {
      tb <- .x
      header_row <- tb[1, ]
      header_row[,] <- NA
      header_row$label <- "Race"
      header_row$row_type <- "label"
      bind_rows(header_row, tb)
    }
  ) %>%
  modify_table_styling(
    rows = label == "**Race**",
    text_format = "bold"
  ) %>%
  modify_table_styling(
    rows = row_type == "level" & variable %in% race_vars,
    indent = 2
  )


tbl1 <- tbl1 %>%
  modify_table_body(
    ~ .x %>%
      mutate(
        row_type = ifelse(variable %in% race_vars, "level", row_type)
      )
  ) %>%
  modify_table_styling(
    rows = variable %in% race_vars,
    indent = 2
  )

tbl1 <- tbl1 %>%
  modify_caption(
    "**Table 1. Clinical characteristics based off diagnosis of current chronic rhinitis at 36 months**"
  )

tbl1

as_gt(tbl1) %>%
  gtsave("~/Desktop/Table1_clinical_characteristics.png")
```
