# CANOE 16S Airway Data Processing
# Last Updated: 5/29/2025
# Elad Deiss-Yehiely, taken from MISS file of Punit Sundar
# DADA2 Processing

```{r}

getwd()
setwd("/wynton/group/lynch/NextSeq_Processed/250113_NS500170_0031_AH7GCTBGYW_20250115_CANOE_Airway_16S_Run2")

```

```{r}

library(dada2)
library(parallel)
library(purrr)
library(DECIPHER)
library(dplyr)
library(tibble)
library(phyloseq)
library(phangorn)
library(msa)

.libPaths()

```

```{r}

out_path <- as.character("/wynton/group/lynch/NextSeq_Processed/250113_NS500170_0031_AH7GCTBGYW_20250115_CANOE_Airway_16S_Run2")
dada2_path <- "/wynton/group/lynch/dada2_files/"
threads <- as.numeric(16) #as.numeric(args[1])
threshold <- 50

```

```{r}

mapping_file <- as.character("SampleSheetRun2.csv") # just name of file

```


```{r}

# Start DADA2 Code
ns_dir <- as.character("241220_NS500170_0029_AH7G5NBGYW_20250107_CANOE_Airway_16S") #as.character(args[2])
save_path <- paste0(out_path, "/dada2_output")
getLines <- min(which(grepl("SampleID", readLines(paste0(out_path, "/", mapping_file), warn=FALSE))))
#map_file <- read.csv(paste0(out_path, "/", mapping_file), skip=getLines-1,row.names=1,sep = "\t" )
#map_file <- read.csv(file.path(out_path, mapping_file), row.names = 1)
map_file <- read.csv(file.path(out_path, mapping_file), skip=20-1,row.names=1)
map_file <- map_file[map_file$Extractor != "Jenny_Lee", ]



print("Save path:")
save_path

# If dada2_result_object.RData already exists, it will be loaded in
if(file.exists(paste0(save_path, "/dada2_result_object.RData"))) { ## If this has already been generated, then it gets loaded in.
  load(paste0(save_path, "/dada2_result_object.RData"))
}

```


```{r}

# Creating lists of forward & reverse reads for filtration step
if(!exists("initial_step")) {
  fnFs <- list() # forward reads
  fnRs <- list() # reverse reads
  filtFs <- list() # filtered forward reads
  filtRs <- list() # filtered reverse reads
  i <- 1
  #dir.create(save_path, showWarnings=FALSE)
  fnFs[[i]] <- list.files(paste0(out_path,"/fastp_submission"), pattern="_R1", full.names=TRUE) # All read 1's
  fnRs[[i]] <- list.files(paste0(out_path,"/fastp_submission"), pattern="_R2", full.names=TRUE) # All read 2's 
  filt_path <- file.path(save_path, "submission_filtered") # this is where filtered results will be stored
  sample.names <- gsub("_S[0-9]+_R1_001.fastq.gz","",basename(fnFs[[i]])) # sample IDs, example: [1] "S33626" "S33627" "S34586" "S34971" "S35299" "S35300" "S37768" "S37880" "S37882" "S37883"
  #sample.names <- gsub("*_R1.fastq.gz","",basename(fnFs[[i]]))
  filtFs[[i]] <- file.path(filt_path, paste0(sample.names, "_R1_filt.fastq.gz")) # This is the path to filtered results + fastq.gz for Read 1's filenames
  filtRs[[i]] <- file.path(filt_path, paste0(sample.names, "_R2_filt.fastq.gz"))
  initial_step <- 1
}

# Assuming `dataframe` is your data frame
# and `sample.names` is your vector of sample names

#rownames_in_sample_names <-  sample.names %in% rownames(map_file)

```



```{r}

# Filter/Trim Step
# This step is a quality control step used to filter out reads based on certain criteria indicated by the parameters used in the filterAndTrim function
# Reads with higher expected errors will be discarded, reads mapping to the phiX genome will be removed, and reads less than minLen will be discarded.
# Ensure that when running on single end, matchIDs parameter is set to FALSE
i <- 1
if(!exists("filterTrimComplete")) {
  print("Begin the Filter and Trim Step")
  length(filtFs[[i]])
  length(fnFs[[i]])
  # Here is some information on some of the parameters used in the next function filterAndTrim :
  # maxEE = After truncation, reads with higher than maxEE "expected errors" will be discarded. 
  # truncQ = Truncate reads at the first instance of a quality score less than or equal to truncQ, 
  # rm.phix = discard reads that match against the phiX genome, 
  # minLen= Remove reads with length less than minLen. minLen is enforced after trimming and truncation.
  # matchIDs: Paired-read filtering only. Whether to enforce matching between the id-line sequence identifiers of the forward and reverse fastq files.
  out <- filterAndTrim(fwd=unlist(fnFs[[i]]), filt=unlist(filtFs[[i]]), rev=unlist(fnRs[[i]]), filt.rev=unlist(filtRs[[i]]),
                       maxEE=2, truncQ=0, rm.phix=TRUE, minLen=50, 
                       compress=TRUE, multithread=threads, verbose=TRUE, matchIDs = TRUE) 
  #out_check <- filterAndTrim(fwd=unlist(fnFs[[i]]), filt=unlist(filtFs[[i]]), rev=unlist(fnRs[[i]]), filt.rev=unlist(filtRs[[i]]),
  #                     maxEE=2, truncQ=0, rm.phix=TRUE, minLen=100, compress=TRUE, multithread=threads, verbose=TRUE, matchIDs = TRUE)
  
  prop.out <- out[,"reads.out"]/out[,"reads.in"]
  out <- cbind(out, prop.out)
  print(out)
  
  keep <- out[,"reads.out"] > threshold
  keep.names <- sample.names[keep] # 352 total samples, 343 samples kept
  if(length(keep.names)<nrow(out)) {
    filtFs[[i]] <- filtFs[[i]][grepl(paste(keep.names, collapse="|"), filtFs[[i]])]
    filtRs[[i]] <- filtRs[[i]][grepl(paste(keep.names, collapse="|"), filtRs[[i]])]
    print(paste("Samples were dropped due to having fewer than", threshold, "reads per sample:"))
    print(paste(rownames(out)[!keep], collapse=","))

  }
  save.image(paste0(save_path, "/dada2_result_object.RData"))
  filterTrimComplete <- 1
} else {
  print("Filter and Trim Already Done")
}

save.image(paste0(save_path, "/dada2_result_object.RData"))


```


```{r}

# Learning error rate for forward and reverse reads 
# This step is needed for the dada function later on in this script
# nbases = The minimum number of total bases to use for error rate learning
# randomize = samples are picked at random from those provided

if(!exists("error_done")) {
  errF <- list()
  errR <- list()
  errF[[i]] <- learnErrors(filtFs[[i]], multithread=threads, randomize=TRUE, nbases=1e8)
  errR[[i]] <- learnErrors(filtRs[[i]], multithread=threads, randomize=TRUE, nbases=1e8)
  error_done <- 1
} else {
  print("Error Checking Complete")
}
save.image(paste0(save_path, "/dada2_result_object.RData"))

# if you want to see error rates, run the following when running this script interactively
#plotErrors(errF[[i]], nominalQ=TRUE)
#plotErrors(errR[[i]], nominalQ=TRUE)


```


```{r}

# Dereplication step
derepFs <- derepFastq(filtFs[[1]], verbose=TRUE)
derepRs <- derepFastq(filtRs[[1]], verbose=TRUE)
# Name the derep-class objects by the sample names
# Make sure to remove those samples that were removed from the filtering step
names(derepFs) <- keep.names
names(derepRs) <- keep.names
#head(derepFs[[i]])

dadaFs <- dada(derepFs, err=errF[[i]], pool=FALSE, multithread=TRUE)
dadaRs <- dada(derepRs, err=errR[[i]], pool=FALSE, multithread=TRUE)

save.image(paste0(save_path, "/dada2_result_object.RData"))
```

```{r}

## NOW Merge Paired Ends # assuming forward & reverse fastq files are in the same order
if(!exists("merge_reads")) {
  print("Merge Paired Reads")
  mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, minOverlap=25, verbose=TRUE)
  #I think this is useful information to print, so I will keep it here.
  head(mergers[[1]])
  str(mergers[[1]])
  dim(mergers[[2]])
  merge_reads <- 1
  save.image(paste0(save_path, "/dada2_result_object.RData"))
  
} else {
  print("Read Merging already Complete")
}


```


```{r}

#Construct Sequence Table
seqtab <- makeSequenceTable(mergers)
dim(seqtab) # 369 62748

#A data check..
print("Initial Sequence Lengths Pre-Chimera Removal")
table(nchar(getSequences(seqtab)))
# Distribution of sequence reads:
seq.length <- sort(table(nchar(getSequences(seqtab))))
#head(getSequences(seqtab))

## Remove Chimeras:

if(!exists("chimera_check")) {
  seqtab.nochim.init <- removeBimeraDenovo(seqtab, method="consensus", multithread=threads, verbose=TRUE)
  dim(seqtab.nochim.init)
  print("Proportion of non-chimeric reads")
  sum(seqtab.nochim.init)/sum(seqtab)
  chimera_check <- 1
} else {print("Chimera Check already complete")}

print("Initial Sequence Lengths")
table(nchar(getSequences(seqtab.nochim.init))) # Moving this to *after* the bimera removal, since it's possible that the odd-sized reads are considered bimera$
seq.length <- as.numeric(names(which.max(table(nchar(getSequences(seqtab.nochim.init))))))
seq.ideal <- seq.int(from=seq.length-5, to=seq.length+5)
seqtab.nochim <- seqtab.nochim.init[, nchar(getSequences(seqtab.nochim.init)) %in% seq.ideal]

write.table(x=getSequences(seqtab.nochim), file=paste0(save_path,"/", ns_dir,"_seqs.txt"), sep="\t", col.names=F, row.names=F, quote=F)
write.table(x=t(seqtab.nochim), file=paste0(save_path,"/",ns_dir,"_otutable.txt"), sep="\t", col.names=T, row.names=T, quote=F)

print("New Sequence Length Distribution")
table(nchar(getSequences(seqtab.nochim)))
# length(getSequences(seqtab.nochim)) # 3871 non-chimeric sequences

save.image(paste0(save_path, "/dada2_result_object.RData"))

getN <- function(x) sum(getUniques(x))
track <- cbind(out, sapply(dadaFs, getN), sapply(dadaRs, getN), sapply(mergers, getN), rowSums(seqtab.nochim))
# If processing a single sample, remove the sapply calls: e.g. replace sapply(dadaFs, getN) with getN(dadaFs)
colnames(track) <- c("reads.in", "reads.out", "prop.out","denoisedF", "denoisedR", "merged", "nonchim")
rownames(track) <- sample.names
head(track)


write.csv(track, paste0(save_path, "/TrackedReadsThruDADA2.csv"))

```

```{r}

## Taxonomy
if(!exists("taxa.print")) {
  print("Running the assignTaxonomy taxonomy Assignment")
  taxa <- assignTaxonomy(seqtab.nochim, paste0(dada2_path, "/silva_nr_v138_train_set.fa.gz"), multithread=threads,
                         tryRC=TRUE, minBoot=80,outputBootstraps=TRUE)
  write.csv(taxa$boot, paste0(save_path, "/TaxonomyBootstraps.csv"), row.names=F)
  taxa <- addSpecies(taxa$tax, paste0(dada2_path, "/silva_species_assignment_v138.fa.gz"), allowMultiple=TRUE,
                     verbose=TRUE,tryRC=TRUE,n=5000)
  taxa.print <- taxa # Removing sequence rownames for display only
  rownames(taxa.print) <- NULL
  table(is.na(taxa.print[,"Genus"]))
} else {print("DADA2 Taxonomy already generated")}

write.table(x=taxa.print, file=paste0(save_path,"/", ns_dir , "_tax_table.txt"), sep="\t", col.names=T, row.names=T, quote=F)

save.image(paste0(save_path, "/dada2_result_object.RData"))

```

```{r}

## Handoff to phyloseq:
seqs <- getSequences(seqtab.nochim)
names(seqs) <- seqs

orig <- seqtab.nochim
rownames(orig) <- sub("_R1_filt.fastq.gz","", rownames(orig)) 
dada2_phyobj <- phyloseq(otu_table(orig, taxa_are_rows=FALSE), tax_table(taxa), sample_data(map_file), DNAStringSet(seqs))
dada2_phyobj
saveRDS(dada2_phyobj, paste0(save_path, "/dada2_phy_obj_raw.rds"))

```
